global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aipal-backend'
    static_configs:
      - targets: ['aipal-backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  - job_name: 'aipal-backend-internal-metrics'
    static_configs:
      - targets: ['aipal-backend:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s